// Each post: { id, slug, theme, tpl, eyebrow, muted?, punch }
// theme: 'page' | 'white' | 'green'
// tpl:   'A' = muted + punch reframe   |   'B' = single statement
// eyebrow: 'fcb' = "For freelancers, creators & business owners"   |   'ent' = "For entrepreneurs"
// In strings: \n = line break, {phrase} = squiggle underline
window.POSTS = [
  { id: '01', slug: 'wrong-tool', theme: 'page', tpl: 'A', eyebrow: 'fcb',
    muted: "You're not bad with money.",
    punch: "You were handed\nthe {wrong tool}." },

  { id: '02', slug: 'willpower', theme: 'white', tpl: 'A', eyebrow: 'ent',
    muted: "You don't have a willpower problem.",
    punch: "You have a {structure}\nproblem." },

  { id: '03', slug: 'fewer-leaks', theme: 'green', tpl: 'A', eyebrow: 'fcb',
    muted: "You don't need more income.",
    punch: "You need\n{fewer leaks}." },

  { id: '04', slug: 'every-deposit', theme: 'green', tpl: 'B', eyebrow: 'fcb',
    punch: "Every deposit,\n{already sorted.}" },

  { id: '05', slug: 'leak-math', theme: 'white', tpl: 'A', eyebrow: 'ent',
    muted: "$7 here. A snack.\nA subscription.",
    punch: "By day 30.\n{$1,000–$2,000 gone.}" },

  { id: '06', slug: 'day1-day30', theme: 'page', tpl: 'A', eyebrow: 'fcb',
    muted: "Day 1 you breathe.",
    punch: "Day 30 you {brace}." },

  { id: '07', slug: 'shame-tool', theme: 'green', tpl: 'A', eyebrow: 'fcb',
    muted: "The shame isn't yours.",
    punch: "It belongs to\n{the tool}." },

  { id: '08', slug: 'calm-feature', theme: 'white', tpl: 'B', eyebrow: 'ent',
    punch: "Calm is a {feature}.\nNot a side effect." },

  { id: '09', slug: 'free-to-try', theme: 'page', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "Free to try.\nBuilt for inconsistent\n{income}." },

  { id: '10', slug: 'money-energy', theme: 'green', tpl: 'A', eyebrow: 'fcb',
    muted: "Money is energy.",
    punch: "Direct it, or\n{it leaks}." },

  { id: '11', slug: 'needed-system', theme: 'page', tpl: 'A', eyebrow: 'ent',
    muted: "I didn't need another\nbudgeting app.",
    punch: "I needed {a system}." },

  { id: '12', slug: 'where-it-is', theme: 'white', tpl: 'A', eyebrow: 'fcb',
    muted: "If the goal is more money,",
    punch: "you need to {know\nwhere it is}." },

  { id: '13', slug: 'guessing', theme: 'glass', tpl: 'A', eyebrow: 'fcb',
    muted: "You're not lazy.",
    punch: "You're {guessing}." },

  { id: '14', slug: 'same-different', theme: 'glass', tpl: 'B', eyebrow: 'ent',
    punch: "Same income.\n{Different feeling}." },

  { id: '15', slug: 'done-thinking', theme: 'glass', tpl: 'A', eyebrow: 'ent',
    muted: "I didn't want to be\na budgeter.",
    punch: "I wanted to be\n{done thinking}." },

  { id: '16', slug: 'white-knuckling', theme: 'glass', tpl: 'B', eyebrow: 'fcb',
    punch: "Permission to stop\n{white-knuckling}." },

  { id: '17', slug: 'budgeting-failing', theme: 'black', tpl: 'A', eyebrow: 'fcb',
    muted: "You're not failing\nat budgeting.",
    punch: "{Budgeting} is\nfailing you." },

  { id: '18', slug: 'leak-not-dramatic', theme: 'black', tpl: 'A', eyebrow: 'fcb',
    muted: "The leak isn't dramatic.",
    punch: "That's why you\n{can't see it}." },

  { id: '19', slug: 'nothing-leaked', theme: 'black', tpl: 'B', eyebrow: 'ent',
    punch: "Bills paid.\nTaxes covered.\n{Nothing leaked.}" },

  { id: '20', slug: 'pricing', theme: 'black', tpl: 'B', eyebrow: 'fcb',
    punch: "$14.99 a month.\nOr $129 a year.\n{Save $50.}" },

  { id: '21', slug: 'day14-problem', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent',
    muted: "It's not a money problem.",
    punch: "It's a {Day 14}\nproblem." },

  { id: '22', slug: 'calm-beats-panic', theme: 'glass-dark', tpl: 'B', eyebrow: 'fcb',
    punch: "{Calm beats panic.}\nSpecific beats vague." },

  { id: '23', slug: 'stop-bracing', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent',
    muted: "The day you\nstop guessing.",
    punch: "Is the day you\n{stop bracing}." },

  { id: '24', slug: 'isnt-yours', theme: 'glass-dark', tpl: 'B', eyebrow: 'fcb',
    punch: "If 30% isn't moved,\n{it isn't yours}." },

  { id: '25', slug: 'freezing', theme: 'white', tpl: 'A', eyebrow: 'fcb',
    muted: "You're not overspending.",
    punch: "You're {freezing}." },

  { id: '26', slug: 'cost-of-starting', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent',
    muted: "The cost of waiting.",
    punch: "Bigger than\nthe cost of {starting}." },

  { id: '27', slug: 'under-instructed', theme: 'page', tpl: 'A', eyebrow: 'fcb',
    muted: "You're not undisciplined.",
    punch: "You're\n{under-instructed}." },

  { id: '28', slug: 'wrong-app', theme: 'black', tpl: 'A', eyebrow: 'ent',
    muted: "You're not behind.",
    punch: "You're using\nthe {wrong app}." },

  { id: '29', slug: 'missing-system', theme: 'green', tpl: 'A', eyebrow: 'fcb',
    muted: "You're not bad at math.",
    punch: "You're missing\n{a system}." },

  { id: '30', slug: 'hard-mode', theme: 'glass', tpl: 'A', eyebrow: 'fcb',
    muted: "Personal finance\nwas built for W-2s.",
    punch: "You're playing on\n{hard mode}." },

  { id: '31', slug: 'protecting', theme: 'white', tpl: 'A', eyebrow: 'fcb',
    muted: "You're not avoiding\nyour bank account.",
    punch: "You're {protecting}\nyourself from it." },

  { id: '32', slug: 'irs-takes', theme: 'black', tpl: 'A', eyebrow: 'ent',
    muted: "A $4,000 deposit\nfeels like $4,000.",
    punch: "$1,200 belongs to\n{the IRS}." },

  { id: '33', slug: 'asks-for-nothing', theme: 'page', tpl: 'A', eyebrow: 'fcb',
    muted: "The best money system.",
    punch: "Asks you for\n{nothing}." },

  { id: '34', slug: 'every-month-guess', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent',
    muted: "Every month\nyou guess.",
    punch: "Another\n{$2,000 gone}." },

  { id: '35', slug: 'yours-isnt', theme: 'green', tpl: 'A', eyebrow: 'fcb',
    muted: "Every budgeting app\nassumes a paycheck.",
    punch: "Yours {isn't}." },

  { id: '36', slug: 'tax-was-never-yours', theme: 'white', tpl: 'A', eyebrow: 'ent',
    muted: "30% of every deposit.",
    punch: "Was never\n{yours}." },

  { id: '37', slug: 'shouldnt-have-to', theme: 'glass', tpl: 'A', eyebrow: 'fcb',
    muted: "Spreadsheets ask you\nto be an accountant.",
    punch: "You {shouldn't}\nhave to be." },

  { id: '38', slug: 'too-late', theme: 'page', tpl: 'A', eyebrow: 'ent',
    muted: "Most apps show what\nalready happened.",
    punch: "By then it's\n{too late}." },

  { id: '39', slug: 'variable-income', theme: 'black', tpl: 'A', eyebrow: 'fcb',
    muted: "It's not\npersonal finance.",
    punch: "It's {variable}\nincome." },

  { id: '40', slug: 'split-stop-bracing', theme: 'glass-dark', tpl: 'B', eyebrow: 'ent',
    punch: "Split every deposit.\n{Stop bracing.}" },

  { id: '41', slug: 'tired-of-bracing', theme: 'page', tpl: 'B', eyebrow: 'ent',
    punch: "I built Able\nso I'd stop\n{bracing}." },

  { id: '42', slug: 'i-froze', theme: 'green', tpl: 'B', eyebrow: 'ent',
    punch: "Built for the\nversion of me\nthat {froze}." },

  { id: '43', slug: 'five-buckets', theme: 'white', tpl: 'A', eyebrow: 'fcb',
    muted: "Taxes. Bills.\nReserve. Debt. Free.",
    punch: "{Five buckets},\nin order." },

  { id: '44', slug: 'move-30', theme: 'glass', tpl: 'A', eyebrow: 'fcb',
    muted: "'Save more'\nisn't a system.",
    punch: "{Move 30%}\non every deposit." },

  { id: '45', slug: 'starting-point', theme: 'glass-dark', tpl: 'A', eyebrow: 'fcb',
    muted: "You don't need\nto be better.",
    punch: "You need\na different\n{starting point}." },

  { id: '46', slug: 'mint-replacement', theme: 'white', tpl: 'A', eyebrow: 'ent',
    muted: "Coming from Mint?",
    punch: "The replacement\n{still assumes}\na paycheck." },

  { id: '47', slug: 'every-dollar-assigned', theme: 'black', tpl: 'A', eyebrow: 'fcb',
    muted: "Asked to assign\nevery dollar.",
    punch: "Money you\n{don't have} yet." },

  { id: '48', slug: 'two-income-households', theme: 'page', tpl: 'A', eyebrow: 'fcb',
    muted: "Built for\ntwo-income\nhouseholds.",
    punch: "Yours {isn't one}." },

  { id: '49', slug: 'doesnt-fix-leak', theme: 'white', tpl: 'A', eyebrow: 'ent',
    muted: "Cancels your\nsubscriptions.",
    punch: "Doesn't fix\n{the leak}." },

  { id: '50', slug: 'before-you-see-it', theme: 'green', tpl: 'A', eyebrow: 'fcb',
    muted: "30% of every deposit.",
    punch: "{Moved} before\nyou see it." },

  { id: '51', slug: 'three-months-slow', theme: 'glass-dark', tpl: 'B', eyebrow: 'ent',
    punch: "Three months of slow.\nWhat does that\n{actually cost}?" },

  { id: '52', slug: 'pay-yourself-wrong', theme: 'black', tpl: 'A', eyebrow: 'fcb',
    muted: "Pay yourself last.",
    punch: "Pay yourself\n{wrong}." },

  { id: '53', slug: 'cpa-didnt-mention', theme: 'glass', tpl: 'B', eyebrow: 'ent',
    punch: "The retirement\nplan your CPA\n{didn't mention}." },

  { id: '54', slug: 'smallest-month', theme: 'page', tpl: 'B', eyebrow: 'fcb',
    punch: "What's the smallest\nmonth you could\n{survive}?" },

  // ── LAUNCH SINGLES (StoryBrand sequence — 55–63) ──
  // Hero / problem / guide / plan / CTA / failure / success.
  // Each is brand-foundational; the cadence schedules these in launch weeks 1–3.

  // 55 — L1 Mon · HERO IDENTIFICATION
  { id: '55', slug: 'income-in-waves', theme: 'page', tpl: 'A', eyebrow: 'fcb',
    muted: "If your income",
    punch: "comes in {waves}.\nThis is for you." },

  // 56 — L1 Thu · INTERNAL PROBLEM (permission to feel seen)
  { id: '56', slug: 'under-equipped', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent',
    muted: "If money makes you freeze,",
    punch: "you're not lazy.\nYou're {under-equipped}." },

  // 57 — L1 Sat · PHILOSOPHICAL PROBLEM
  { id: '57', slug: 'wrong-tool-handed', theme: 'green', tpl: 'A', eyebrow: 'fcb',
    muted: "You're not bad with money.",
    punch: "You've been handed\n{the wrong tool}." },

  // 58 — L2 Mon · PROBLEM PEAK (the loop)
  { id: '58', slug: 'the-loop', theme: 'black', tpl: 'A', eyebrow: 'fcb',
    muted: "Day 14: brace.\nDay 30: blame.",
    punch: "Day 1: {forget}\nyou ever blamed." },

  // 59 — L2 Thu · PHILOSOPHICAL ("you shouldn't have to")
  { id: '59', slug: 'not-a-cfo', theme: 'white', tpl: 'A', eyebrow: 'fcb',
    muted: "You shouldn't have to be a CFO",
    punch: "to have\n{a calm month}." },

  // 60 — L2 Sat · BRIDGE (boring on purpose)
  { id: '60', slug: 'boring-on-purpose', theme: 'page', tpl: 'A', eyebrow: 'ent',
    muted: "Boring is the goal.",
    punch: "{Specific} is how\nyou get there." },

  // 61 — L3 Mon · PLAN (split first, spend last)
  { id: '61', slug: 'split-first', theme: 'green', tpl: 'A', eyebrow: 'fcb',
    muted: "One pile.\nFive jobs.",
    punch: "{Split first.}\nSpend last." },

  // 62 — L3 Thu · FAILURE AVOIDED
  { id: '62', slug: 'april-surprise-shame', theme: 'black', tpl: 'A', eyebrow: 'fcb',
    muted: "What you avoid:",
    punch: "{April. Surprise.\nShame.}" },

  // 63 — L3 Sat · CTA CLOSE
  { id: '63', slug: 'free-seven-days', theme: 'green', tpl: 'B', eyebrow: 'fcb', center: true,
    punch: "Free for {7 days}.\n{becomeable.app}" },
];


// ─────────────────────────────────────────────────────────
// CAROUSELS — each carousel shares a theme across slides
// Slide fields: tpl, eyebrow (custom string OK), muted?, punch, meta (footer-right text)
// ─────────────────────────────────────────────────────────
window.CAROUSELS = [
  // C1 — Why budgeting apps fail freelancers (white · website CTA)
  { id: 'C1', slug: 'apps-fail-freelancers', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Why budgeting\napps fail\n{freelancers}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Most apps assume\na paycheck.",
        punch: "Yours {isn't}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "They show what\nalready happened.",
        punch: "By then it's\n{too late}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Spreadsheets ask you\nto be an accountant.",
        punch: "You {shouldn't}\nhave to be.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "The problem\nisn't you.",
        punch: "It's the\n{assumption}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Variable income\nneeds a system.",
        punch: "That starts\nthe {second}\nit hits.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C2 — Day 1-31 arc (multi: page → black → green · free-trial CTA)
  { id: 'C2', slug: 'freelancer-month', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "A freelancer's\nmonth.",
        meta: '1 / 8' },
      { tpl: 'A', eyebrow: 'Day 1',
        muted: "Deposit hits.",
        punch: "You {breathe}.",
        meta: '2 / 8' },
      { tpl: 'A', eyebrow: 'Day 7',
        muted: "A snack.\nA subscription.",
        punch: "You stop {checking}.",
        meta: '3 / 8' },
      { tpl: 'A', eyebrow: 'Day 14', theme: 'black',
        muted: "The leak.",
        punch: "You feel it.\n{Can't name it.}",
        meta: '4 / 8' },
      { tpl: 'A', eyebrow: 'Day 30', theme: 'black',
        muted: "You check the balance.",
        punch: "Where did\n{$4,000} go?",
        meta: '5 / 8' },
      { tpl: 'A', eyebrow: 'Day 31', theme: 'black',
        muted: "Shame. Guilt.",
        punch: "{Repeat.}",
        meta: '6 / 8' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "It's not a\nwillpower problem.",
        punch: "It's a {Day 1}\nproblem.",
        meta: '7 / 8' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C3 — Five buckets (brand green · pricing CTA)
  { id: 'C3', slug: 'five-buckets', theme: 'green', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Every dollar\ngets {a job}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'Bucket 1',
        muted: "Taxes.",
        punch: "About {30%}.\nNot yours.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'Bucket 2',
        muted: "Bills.",
        punch: "Spread across\n{months}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Bucket 3',
        muted: "Reserve.",
        punch: "Slow months\ndon't feel\n{slow}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'Bucket 4',
        muted: "Debt.",
        punch: "Killed on\na {schedule}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'Bucket 5',
        muted: "Free.",
        punch: "Spend without\n{flinching}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C4 — Where $4,000 goes (cloud black · website CTA)
  { id: 'C4', slug: 'where-4000-goes', theme: 'black', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Where {$4,000}\nactually goes.",
        meta: '1 / 8' },
      { tpl: 'A', eyebrow: 'Tax',
        muted: "$1,200.",
        punch: "Belongs to\n{the IRS}.",
        meta: '2 / 8' },
      { tpl: 'A', eyebrow: 'Bills',
        muted: "$1,800.",
        punch: "Rent, utilities,\n{insurance}.",
        meta: '3 / 8' },
      { tpl: 'A', eyebrow: 'Subscriptions',
        muted: "$300.",
        punch: "You forgot\n{half} of them.",
        meta: '4 / 8' },
      { tpl: 'A', eyebrow: 'Food',
        muted: "$400.",
        punch: "{I'll just grab.}",
        meta: '5 / 8' },
      { tpl: 'A', eyebrow: 'Unclassified',
        muted: "$300.",
        punch: "{The leak.}",
        meta: '6 / 8' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "The leak\nfeels small.",
        punch: "The {compound}\nis huge.",
        meta: '7 / 8' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C5 — Tax math 1099 (white · free-trial CTA)
  { id: 'C5', slug: 'tax-math-1099', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "If you're 1099,\nread {this}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Roughly 30%\nof every deposit.",
        punch: "Belongs to\n{the IRS}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Not in April.",
        punch: "{The second}\nit clears.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "If you don't move it.",
        punch: "You'll {spend} it.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "April hits.",
        punch: "The {bill}\nis real.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Fix: a tax bucket.",
        punch: "Fills {automatically}.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C6 — Freezing to flowing (multi: page → glass → green · pricing CTA)
  { id: 'C6', slug: 'freezing-to-flowing', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How freelancers\nstop {freezing}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'Step 1',
        muted: "Stop treating\nit as money.",
        punch: "Treat it as\n{energy}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'Step 2',
        muted: "Move taxes.",
        punch: "{First.} Always.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Step 3', theme: 'glass',
        muted: "Cover bills.",
        punch: "Before you\n{feel like it}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'Step 4', theme: 'glass',
        muted: "Spread\nacross months.",
        punch: "Slow months\ndon't feel\n{slow}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'Step 5', theme: 'green',
        muted: "Spend\nwhat's left.",
        punch: "Without {flinching}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C7 — Founder story (page · website CTA)
  // C7 — REMOVED 2026-04-26 (founder-story carousel; per user feedback)

  // C8 — 5 signs working (glass · free-trial CTA)
  { id: 'C8', slug: '5-signs-working', theme: 'glass', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "5 signs your\nmoney system\nis {working}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'Sign 1',
        muted: "Open your bank app.",
        punch: "Without {bracing}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'Sign 2',
        muted: "Know your\ntax number.",
        punch: "Without {checking}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Sign 3',
        muted: "Slow months.",
        punch: "Don't feel {slow}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'Sign 4',
        muted: "Spend\nthe free bucket.",
        punch: "Without {guilt}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'Sign 5',
        muted: "Year-end.",
        punch: "Not panic.\n{Just Tuesday.}",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C9 — Three personas (multi: page → dark → green · pricing CTA)
  { id: 'C9', slug: 'three-personas', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Which one\nare {you}?",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'Type 1', theme: 'glass-dark',
        muted: "The Freezer.",
        punch: "Moving it\n{makes it real}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'Type 2', theme: 'black',
        muted: "The Leaker.",
        punch: "Day 30.\n{It's gone.}",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Type 3', theme: 'glass-dark',
        muted: "The Shame Cycle.",
        punch: "Relief. Leak.\nPanic. {Shame.}",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "All three\nare structural.",
        punch: "Not {personal}.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "A system that\nruns {without you}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C10 — "Save more" reframe (cloud black · website CTA)
  { id: 'C10', slug: 'save-more', theme: 'black', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "'Save more'\nisn't a {plan}.",
        meta: '1 / 7' },
      { tpl: 'B', eyebrow: 'ent',
        punch: "It's a {wish}\ndressed as advice.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Saving requires\nleft over.",
        punch: "Variable income\nrarely {has it}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "The fix isn't\nmore discipline.",
        punch: "It's a different\n{order}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Move savings first.",
        punch: "Spend {what's left}.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'ent',
        punch: "Same money.\nReverse the {order}.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C11 — Math of waiting (multi: page → dark → green · free-trial CTA)
  { id: 'C11', slug: 'math-of-waiting', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "The cost\nof {waiting}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'Per month',
        muted: "Average leak.",
        punch: "About {$2,000}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'Six months', theme: 'glass-dark',
        muted: "Of waiting.",
        punch: "About {$12,000}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'One year', theme: 'black',
        muted: "Of waiting.",
        punch: "About {$24,000}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'black',
        muted: "Not bad\nwith money.",
        punch: "A {missing}\nsystem.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "The math\nchooses {for you}.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C12 — First week with Able (page · pricing CTA)
  { id: 'C12', slug: 'first-week', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Your first week\nwith {Able}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'Day 1',
        muted: "Connect your account.",
        punch: "Set your\n{tax %}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'Day 2',
        muted: "Pick your bills.",
        punch: "{Spread}\nacross months.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Day 3',
        muted: "Add your debt.",
        punch: "{Schedule} it.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'Day 4',
        muted: "Set your\nreserve target.",
        punch: "Slow months\ncovered {early}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'Day 5',
        muted: "Whatever's left.",
        punch: "Is {free}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C13 — April without panic (glass-dark · website CTA)
  { id: 'C13', slug: 'april-no-panic', theme: 'glass-dark', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "April without\nthe {panic}.",
        meta: '1 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "If you've been\nmoving 30%.",
        punch: "Since {January}.",
        meta: '2 / 6' },
      { tpl: 'B', eyebrow: 'ent',
        punch: "The {bill}\nis already paid.",
        meta: '3 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "April is\njust paperwork.",
        punch: "Not a {financial}\nevent.",
        meta: '4 / 6' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Guessing,\nor a {system}.",
        meta: '5 / 6' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C14 — Monthly or annual? (glass · free-trial CTA)
  { id: 'C14', slug: 'monthly-or-annual', theme: 'glass', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Monthly or\n{annual}?",
        meta: '1 / 6' },
      { tpl: 'A', eyebrow: 'Monthly',
        muted: "$14.99 a month.",
        punch: "Cancel {anytime}.",
        meta: '2 / 6' },
      { tpl: 'A', eyebrow: 'Annual',
        muted: "$129 a year.",
        punch: "Save {$50}.",
        meta: '3 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Annual is for:",
        punch: "Committing\n{all year}.",
        meta: '4 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Monthly is for:",
        punch: "Wanting to\n{try it} first.",
        meta: '5 / 6' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "{Free} for 7 days.\nThen pick\neither one.",
        meta: 'becomeable.app' },
  ] },

  // C15 — What Able is NOT (white · pricing CTA)
  { id: 'C15', slug: 'what-able-isnt', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Things Able\n{doesn't} do.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'Not',
        muted: "Investment advice.",
        punch: "Not {crypto}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'Not',
        muted: "A credit card.",
        punch: "Not {a bank}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Not',
        muted: "Another\nspreadsheet.",
        punch: "You'll {abandon}\nin March.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'Not',
        muted: "We don't yell at you.",
        punch: "About {lattes}.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Just one thing:\nsplit every {deposit}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C16 — Feast or famine cycle (multi: page → black → green · free trial)
  { id: 'C16', slug: 'feast-or-famine', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "The feast\nor {famine}\ncycle.",
        meta: '1 / 8' },
      { tpl: 'A', eyebrow: 'Feast',
        muted: "A big check lands.",
        punch: "You feel\n{rich}.",
        meta: '2 / 8' },
      { tpl: 'A', eyebrow: 'Famine', theme: 'black',
        muted: "Three weeks\nof nothing.",
        punch: "{Panic.} Drain.",
        meta: '3 / 8' },
      { tpl: 'A', eyebrow: 'Repeat', theme: 'black',
        muted: "Then another feast.",
        punch: "Then another\n{famine}.",
        meta: '4 / 8' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'black',
        muted: "It's not discipline.",
        punch: "It's a {missing}\nstructure.",
        meta: '5 / 8' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "Route every deposit.",
        punch: "{Five accounts.}\nSpecific jobs.",
        meta: '6 / 8' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "Same money.\n{More work.}",
        meta: '7 / 8' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C17 — How to budget as a freelancer (white · website)
  { id: 'C17', slug: 'freelancer-budget', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How to budget\nas a {freelancer}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Last month: $7,400.",
        punch: "Month before:\n{$3,100}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Budget your\nbest month.",
        punch: "{Overspend.}\nThen broke.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "It's not\ndiscipline.",
        punch: "It's {fear} of\nthe empty week.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Stop thinking\nabout the month.",
        punch: "Think about\nthe {deposit}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Tax. Bills.\nReserve. Debt. Free.",
        punch: "{Five jobs.}\nIn order.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C18 — Pay yourself a steady paycheck (green · pricing)
  { id: 'C18', slug: 'steady-paycheck', theme: 'green', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Your income\nis lumpy.\nYour bills {are not}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Underpay:\nfeel broke.",
        punch: "Overpay:\n{scramble}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "The smoothing\nreserve.",
        punch: "{A dam}\non a river.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Pay yourself.",
        punch: "{75%} of your\n12-month average.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Same paycheck.\nSame day.",
        punch: "{Boring} is\nthe feature.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Bad months\nstill happen.",
        punch: "They land on\n{the reserve}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C19 — Creator's budget (glass · free trial)
  { id: 'C19', slug: 'creator-budget', theme: 'glass', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Creator income\nis {five incomes}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Platform. Brand deals.\nMerch. Subs.",
        punch: "{Pretending}\nto be one.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "The algorithm\nis a black box.",
        punch: "So you {freeze}\ninstead.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "A viral month.",
        punch: "Not your new {normal}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Pay yourself a number.",
        punch: "Below {best}.\nAbove {worst}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Rollercoaster\nto a life.",
        punch: "Same number.\n{Same day.}",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C20 — Designer / developer income system (white · pricing)
  { id: 'C20', slug: 'designer-developer', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How {designers}\nand devs budget.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Project-based income.",
        punch: "Has {gaps}\nbetween projects.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Net-60 invoices.",
        punch: "You're funding\n{their} business.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Your Floor.",
        punch: "The number that\n{doesn't change}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Everything else.",
        punch: "Is {negotiable}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Tax. Floor. Reserve.\nThen yours.",
        punch: "{In order.}\nEvery deposit.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C21 — Real estate agent commission system (black · website)
  { id: 'C21', slug: 'real-estate-agent', theme: 'black', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How agents\nbudget {commission}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Commission lands.",
        punch: "Half is the {brokerage}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Deals fall through.",
        punch: "Chargebacks\n{reverse} commissions.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Q4 closes.",
        punch: "What you worked\nin {Q3}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Route every check.",
        punch: "Tax. Floor.\n{Reserve.}",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Slow seasons.\nNo {scrambling}.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C22 — Rideshare driver income system (page · free trial)
  { id: 'C22', slug: 'rideshare-driver', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How drivers\nbudget {gig income}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Income is daily.",
        punch: "And {fragile}.\nWeather-dependent.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Your gross.",
        punch: "Is not your\n{take-home}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Maintenance.\nReplacement.",
        punch: "Your biggest\n{hidden cost}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Set 25% aside.",
        punch: "{Before} you see it.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Rainy days.\nFunded {early}.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C23 — Etsy seller income system (glass-dark · pricing)
  { id: 'C23', slug: 'etsy-seller', theme: 'glass-dark', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How sellers\nbudget {Etsy income}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Q4 is 40%\nof revenue.",
        punch: "The other 9 months.\n{Spread thin.}",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Inventory cash.",
        punch: "Sits in products.\nNot {accounts}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Platform fees.\nReturns.",
        punch: "1099-K shows\n{the gross}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Tax bucket.\nFunded automatically.",
        punch: "From {every}\ndeposit.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Q4 funds\nthe {other 9}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C24 — Coach / consultant (green · website)
  { id: 'C24', slug: 'coach-consultant', theme: 'green', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How coaches\nbudget {sessions}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Session income.",
        punch: "Predictable\n{until} it isn't.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "A referral drought.",
        punch: "Can last\n{weeks}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Insurance delays.",
        punch: "{Predictable}\nfriction.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Income reserve.",
        punch: "Bills paid\nin {dry weeks}.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Stop taking\n{any} client.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C25 — Commission income survival (black · free trial)
  { id: 'C25', slug: 'commission-income', theme: 'black', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Commission\n{survival guide}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Commission is a job.",
        punch: "Where the rules\n{change} monthly.",
        meta: '2 / 7' },
      { tpl: 'B', eyebrow: 'ent',
        punch: "If I just had\nthree good months\n{in a row}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "You're not\nbad with money.",
        punch: "You're using\nthe {wrong brain}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Route every check.",
        punch: "Tax. Bills.\n{Reserve.}",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Slow months.\n{Funded ahead.}",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C26 — The self-employed emergency fund (glass-dark · pricing)
  { id: 'C26', slug: 'emergency-fund', theme: 'glass-dark', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Three months\nisn't {enough}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Standard advice.",
        punch: "{3 to 6 months.}\nNot for you.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "No unemployment.\nNo severance.",
        punch: "{No paid leave.}",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Your baseline.",
        punch: "{Includes the shocks.}",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Aim for",
        punch: "{9 months}\nof bills covered.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Slow quarters\n{don't threaten}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C27 — How much to set aside for taxes (white · website)
  { id: 'C27', slug: 'tax-set-aside', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How much\nfor {taxes}?",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "You pay\ntwo taxes.",
        punch: "Federal {plus}\nself-employment.",
        meta: '2 / 7' },
      { tpl: 'B', eyebrow: 'ent',
        punch: "Self-employment.\n{15.3%} flat.\nOn every dollar.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Most land between.",
        punch: "{25 and 35%}\nof every deposit.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Last year's tax.\nDivided by income.",
        punch: "Add state.\n{Plus 3 points.}",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "If you guess.",
        punch: "{Err high.}\nA refund beats a bill.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C28 — What is a 1099-NEC? (white · free trial)
  { id: 'C28', slug: '1099-nec', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "What is\na {1099-NEC}?",
        meta: '1 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "The 1099-NEC.",
        punch: "Issued by\n{clients}.\nNot platforms.",
        meta: '2 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Threshold:",
        punch: "{$600.}\nNo minimum.",
        meta: '3 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Didn't get one?",
        punch: "The {IRS} did.",
        meta: '4 / 6' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Track every payment.",
        punch: "Tie out at {year-end}.",
        meta: '5 / 6' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C29 — What is a 1099-K? (white · pricing)
  { id: 'C29', slug: '1099-k', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "What is\na {1099-K}?",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Stripe. PayPal.\nVenmo. Etsy.",
        punch: "All issue\n{1099-Ks}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "The number shown.",
        punch: "Is {gross}.\nNot net.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Common mistake:",
        punch: "Pay tax on {gross}.\nOverpay.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "By 2026:",
        punch: "{$600.}\nEverywhere.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Reconcile fees.\nReturns. Refunds.",
        punch: "Pay tax on\n{net profit}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C30 — Quarterly taxes during a bad month (glass-dark · website)
  { id: 'C30', slug: 'bad-month-quarterly', theme: 'glass-dark', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Quarterlies due.\n{Bad month.}",
        meta: '1 / 6' },
      { tpl: 'B', eyebrow: 'ent',
        punch: "The IRS\n{does not care}.",
        meta: '2 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Underpayment penalty.",
        punch: "About {9%}\nannually.",
        meta: '3 / 6' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Pay what you can.",
        punch: "Better than\n{nothing}.",
        meta: '4 / 6' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Prevention:",
        punch: "A reserve\nfor {lean months}.",
        meta: '5 / 6' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C31 — The home office deduction (page · free trial)
  { id: 'C31', slug: 'home-office', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "The home office\n{deduction}.",
        meta: '1 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Two methods.",
        punch: "Simplified\nor {actual}.",
        meta: '2 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Simplified.",
        punch: "{$5} per sq ft.\nQuick math.",
        meta: '3 / 6' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Actual.",
        punch: "Document {everything}.\nUsually bigger.",
        meta: '4 / 6' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Picking?",
        punch: "{Run both} numbers.\nTake the bigger.",
        meta: '5 / 6' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C32 — Schedule C walkthrough (white · pricing)
  { id: 'C32', slug: 'schedule-c', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "{Schedule C}\nin 6 slides.",
        meta: '1 / 7' },
      { tpl: 'B', eyebrow: 'ent',
        punch: "The form\nwhere your {business}\nlives.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'Line 1',
        muted: "Gross income.",
        punch: "Everything\nthat {came in}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Lines 4-6',
        muted: "Cost of\ngoods sold.",
        punch: "Materials.\n{Inventory.}",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'Lines 8-27',
        muted: "Expenses.",
        punch: "Rent. Software.\n{Phone.} Travel.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'Line 31',
        muted: "Net profit.",
        punch: "What gets {taxed}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C33 — Self-employment tax deductions (glass · website)
  { id: 'C33', slug: 'se-deductions', theme: 'glass', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Deductions\nyou might {miss}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'Deduction 1',
        muted: "Health insurance.",
        punch: "{Premiums}\nfully deductible.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'Deduction 2',
        muted: "Self-employment tax.",
        punch: "{Half of it}\ndeductible.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Deduction 3',
        muted: "Vehicle.",
        punch: "{Mileage} or actual.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'Deduction 4',
        muted: "Equipment.",
        punch: "Computer. {Software.}\nPhone. Tools.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'Deduction 5',
        muted: "Retirement.",
        punch: "{SEP-IRA.}\nFully deductible.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C34 — Get out of debt on inconsistent income (multi: black → green · free trial)
  { id: 'C34', slug: 'get-out-of-debt', theme: 'black', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Debt with\n{variable} income.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "The treadmill.",
        punch: "Pay minimums.\n{Stay the same.}",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Every debt book.",
        punch: "Assumes\n{steady income}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Yours isn't.",
        punch: "So those plans\n{break} fast.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "The strategy.",
        punch: "The reserve covers\n{minimums}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "Good months.",
        punch: "Attack {principal}.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C35 — Improve your credit score (page · pricing)
  { id: 'C35', slug: 'credit-score', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Your credit\nin {6 slides}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Many factors.",
        punch: "Two {dominate}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'First',
        muted: "Payment history.",
        punch: "{35%} of your score.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Second',
        muted: "Credit utilization.",
        punch: "{30%.} Keep below 10%.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'Quick win',
        muted: "Pay balances down.",
        punch: "{30 to 60} points.\nIn 30 days.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Automate everything.\n{Never miss.}",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // C36 — Pay yourself first (the variable-income version) (green · website)
  { id: 'C36', slug: 'pay-yourself-first', theme: 'green', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Pay {yourself}\nfirst.",
        meta: '1 / 7' },
      { tpl: 'B', eyebrow: 'ent',
        punch: "Most entrepreneurs\nare their own\n{last priority}.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "You're running.",
        punch: "A job that pays\n{others}.",
        meta: '3 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Money follows\n{structure}.\nNot hope.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Start with 5%.",
        punch: "{Beats zero}\nby infinity.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Different account.",
        punch: "Not your\n{operating} one.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Built for\ninconsistent\n{income}.",
        meta: 'becomeable.app' },
  ] },

  // C37 — How money actually works (glass · free trial)
  { id: 'C37', slug: 'how-money-works', theme: 'glass', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How money\n{actually} works.",
        meta: '1 / 7' },
      { tpl: 'B', eyebrow: 'ent',
        punch: "Money is a {skill}.\nNot a personality.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Nobody taught you.",
        punch: "{Not your fault.}",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'Rule of 72',
        muted: "Divide 72\nby the rate.",
        punch: "Years until\nyour money\n{doubles}.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'At 1%',
        muted: "Savings.",
        punch: "Doubles every\n{72 years}.",
        meta: '5 / 7' },
      { tpl: 'A', eyebrow: 'At 8%',
        muted: "Stock market.",
        punch: "Doubles every\n{9 years}.",
        meta: '6 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "{Free} for 7 days.\nBuilt for\nvariable income.",
        meta: 'becomeable.app' },
  ] },

  // C38 — Get business funding without losing it (black · pricing)
  { id: 'C38', slug: 'business-funding', theme: 'black', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Business funding.\nWithout {losing it}.",
        meta: '1 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "Of small business loans.",
        punch: "{80%} get denied.",
        meta: '2 / 7' },
      { tpl: 'A', eyebrow: 'ent',
        muted: "The reasons.",
        punch: "Are all\n{fixable}.",
        meta: '3 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "Personal vs\nbusiness credit.",
        punch: "{Two systems.}\nKnow both.",
        meta: '4 / 7' },
      { tpl: 'A', eyebrow: 'PAYDEX',
        muted: "D&B's score.",
        punch: "Lenders want\n{80 plus}.",
        meta: '5 / 7' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "Set up the\nbusiness {first}.",
        meta: '6 / 7' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Save $50.}",
        meta: 'becomeable.app' },
  ] },

  // ── LAUNCH CAROUSELS (StoryBrand sequence — C39–C44) ──

  // C39 — L1 Wed · PERSONAS DEEP DIVE (three kinds of broke at Day 30)
  { id: 'C39', slug: 'three-kinds-of-broke', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Three kinds\nof broke at\n{Day 30}.",
        meta: '1 / 8' },
      { tpl: 'A', eyebrow: 'Type 1', theme: 'glass-dark',
        muted: "The Freezer.",
        punch: "Money came.\n{Never moved.}",
        meta: '2 / 8' },
      { tpl: 'A', eyebrow: 'Type 2', theme: 'black',
        muted: "The Leaker.",
        punch: "Came in.\n{Dissolved.}",
        meta: '3 / 8' },
      { tpl: 'A', eyebrow: 'Type 3', theme: 'glass-dark',
        muted: "The Shame Cycler.",
        punch: "Relief. Spend.\n{Hate. Repeat.}",
        meta: '4 / 8' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "Same person.\n{Different week.}",
        meta: '5 / 8' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "It's not willpower.",
        punch: "It's the\n{wrong tool}.",
        meta: '6 / 8' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "Built for you —",
        punch: "if your paycheck\n{doesn't exist}.",
        meta: '7 / 8' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Free for 7.}",
        meta: 'becomeable.app' },
  ] },

  // C40 — L1 Fri · WHY APPS FAIL YOU (philosophical pain)
  { id: 'C40', slug: 'built-wrong-for-you', theme: 'white', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Why apps fail\n{you specifically}.",
        meta: '1 / 8' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "They assume",
        punch: "a {paycheck}.\nYours doesn't exist.",
        meta: '2 / 8' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "They give you envelopes",
        punch: "for {next month}.\nYou don't know yet.",
        meta: '3 / 8' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "They expect",
        punch: "a {fixed surplus}.\nYou have variable.",
        meta: '4 / 8' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "They tell you to",
        punch: "{save more}.\nThat's a wish.",
        meta: '5 / 8' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "You don't need\nmore {discipline}.",
        meta: '6 / 8' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "You need a system\n{that doesn't pretend}.",
        meta: '7 / 8' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Free for 7.}",
        meta: 'becomeable.app' },
  ] },

  // C41 — REMOVED 2026-04-26 (how-i-lost-40k founder carousel; per user feedback)

  // C42 — L2 Fri · SUCCESS PREVIEW (what calm feels like)
  { id: 'C42', slug: 'calm-month', theme: 'glass', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "What a {calm}\nmonth actually\nfeels like.",
        meta: '1 / 8' },
      { tpl: 'A', eyebrow: 'Day 1',
        muted: "Deposit lands.",
        punch: "{Already sorted.}\nNothing to decide.",
        meta: '2 / 8' },
      { tpl: 'A', eyebrow: 'Day 7',
        muted: "First bill auto-pays.",
        punch: "You {don't think}\nabout it.",
        meta: '3 / 8' },
      { tpl: 'A', eyebrow: 'Day 14',
        muted: "You open Able.",
        punch: "{Smile.} Close it.\nNothing's wrong.",
        meta: '4 / 8' },
      { tpl: 'A', eyebrow: 'Day 30',
        muted: "End of month.",
        punch: "{No surprises.}\nApril-proof.",
        meta: '5 / 8' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "This is\n{calm-specific}.",
        meta: '6 / 8' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "Boring on purpose.\n{Specific by design.}",
        meta: '7 / 8' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "Free for 7 days.",
        punch: "$14.99/mo.\n{Or $129/yr.}",
        meta: 'becomeable.app' },
  ] },

  // C43 — L3 Wed · THE PLAN (how Able works in 8 slides)
  { id: 'C43', slug: 'how-able-works', theme: 'green', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How {Able}\nworks in 8\nslides.",
        meta: '1 / 8' },
      { tpl: 'A', eyebrow: 'Step 1', theme: 'page',
        muted: "Connect a bank.",
        punch: "Or don't.\n{Manual works.}",
        meta: '2 / 8' },
      { tpl: 'A', eyebrow: 'Step 2', theme: 'page',
        muted: "Tell Able",
        punch: "your {expected}\nincome.",
        meta: '3 / 8' },
      { tpl: 'A', eyebrow: 'Step 3', theme: 'page',
        muted: "Pick your buckets.",
        punch: "{Defaults work.}\n8 minutes.",
        meta: '4 / 8' },
      { tpl: 'A', eyebrow: 'Step 4', theme: 'page',
        muted: "Each deposit",
        punch: "{auto-allocates.}\nBefore you see it.",
        meta: '5 / 8' },
      { tpl: 'A', eyebrow: 'Step 5', theme: 'page',
        muted: "Coach pings you",
        punch: "when something\n{looks off}.",
        meta: '6 / 8' },
      { tpl: 'B', eyebrow: 'fcb',
        punch: "That's it.\n{That's the system.}",
        meta: '7 / 8' },
      { tpl: 'A', eyebrow: 'fcb',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Free for 7.}",
        meta: 'becomeable.app' },
  ] },

  // C45 — Brand-script · HOW BREATHING AGAIN WORKS (homepage feature walkthrough)
  { id: 'C45', slug: 'how-breathing-again-works', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "How {breathing}\nagain works.",
        meta: '1 / 6' },
      { tpl: 'A', eyebrow: 'Step 1',
        muted: "Log what came in.",
        punch: "Ten seconds.\n{Any amount.}\nAny source.",
        meta: '2 / 6' },
      { tpl: 'A', eyebrow: 'Step 2', theme: 'green',
        muted: "Able tells you\nwhere it goes.",
        punch: "Bills. Debt.\nSavings. {Free.}",
        meta: '3 / 6' },
      { tpl: 'A', eyebrow: 'Step 3', theme: 'green',
        muted: "Tap each move off",
        punch: "once you've done it.\n{Little dopamine hit.}",
        meta: '4 / 6' },
      { tpl: 'B', eyebrow: 'ent', theme: 'glass',
        punch: "Debt drops.\nSavings grow.\n{The fear fades.}",
        meta: '5 / 6' },
      { tpl: 'A', eyebrow: 'ent', theme: 'green',
        muted: "$14.99 a month.",
        punch: "Or $129 a year.\n{Free for 7.}",
        meta: 'becomeable.app' },
  ] },

  // C44 — L3 Fri · TRANSFORMATION (Day 1 → Day 90)
  { id: 'C44', slug: 'day-1-to-90', theme: 'page', slides: [
      { tpl: 'B', eyebrow: 'Swipe →',
        punch: "Day 1\nto Day 90\nwith {Able}.",
        meta: '1 / 8' },
      { tpl: 'A', eyebrow: 'Day 1',
        muted: "Setup.",
        punch: "{8 minutes.}\nThat's all.",
        meta: '2 / 8' },
      { tpl: 'A', eyebrow: 'Day 7',
        muted: "First auto-allocation.",
        punch: "{Felt weird.}\nIn a good way.",
        meta: '3 / 8' },
      { tpl: 'A', eyebrow: 'Day 14',
        muted: "First bill",
        punch: "{paid itself.}\nYou forgot it existed.",
        meta: '4 / 8' },
      { tpl: 'A', eyebrow: 'Day 30',
        muted: "You don't open it",
        punch: "for {three days}.\nThat's the win.",
        meta: '5 / 8' },
      { tpl: 'A', eyebrow: 'Day 60',
        muted: "First calm month.",
        punch: "No bracing.\n{No leak.}",
        meta: '6 / 8' },
      { tpl: 'B', eyebrow: 'fcb', theme: 'green',
        punch: "Day 90.\n{You don't recognize}\npast-you.",
        meta: '7 / 8' },
      { tpl: 'A', eyebrow: 'fcb', theme: 'green',
        muted: "Free for 7 days.",
        punch: "{becomeable.app}",
        meta: 'becomeable.app' },
  ] },
];


// ─────────────────────────────────────────────────────────
// BRANDSCRIPT — phrases lifted verbatim from the brand script.
// These are the canonical messaging beats: lockup, North Star,
// audience, villain, fear, paralysis, permission, solution,
// outcomes, transformation, identity. Edit the text here to
// keep the brand voice consistent across every other post.
// ─────────────────────────────────────────────────────────
window.BRANDSCRIPT = [

  // ── Brand lockup ──
  { id: 'B01', slug: 'lockup-built-for', cat: 'Brand lockup', theme: 'green', tpl: 'B', eyebrow: 'fcb', center: true,
    punch: "Built for\n{inconsistent income.}" },

  { id: 'B02', slug: 'lockup-budget-with', cat: 'Brand lockup', theme: 'page', tpl: 'B', eyebrow: 'fcb', center: true,
    punch: "Budget with an\n{inconsistent income.}" },

  { id: 'B03', slug: 'lockup-app-built-for', cat: 'Brand lockup', theme: 'white', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "An app built for entrepreneurs",
    punch: "who struggle to\n{budget inconsistent income.}" },

  // ── North Star ──
  { id: 'B04', slug: 'north-star', cat: 'North Star', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "We help entrepreneurs\nbudget inconsistent income",
    punch: "so they can {pay down debt},\nsave, and stop living\nunpredictable check\nto unpredictable check." },

  // ── Audience ──
  { id: 'B05', slug: 'audience-struggles-to-budget', cat: 'Audience', theme: 'page', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "For the entrepreneur",
    punch: "who struggles to budget\n{inconsistent income.}" },

  { id: 'B06', slug: 'audience-cant-budget', cat: 'Audience', theme: 'white', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "For entrepreneurs",
    punch: "who can't budget\n{inconsistent income.}" },

  { id: 'B07', slug: 'audience-built-for-ents', cat: 'Audience', theme: 'green', tpl: 'B', eyebrow: 'ent',
    punch: "Built for {entrepreneurs}\nwith inconsistent income." },

  { id: 'B08', slug: 'audience-people', cat: 'Audience', theme: 'page', tpl: 'B', eyebrow: 'fcb',
    punch: "For people with\n{inconsistent income.}" },

  // ── Villain / problem ──
  { id: 'B09', slug: 'villain-no-one-taught', cat: 'Villain', theme: 'black', tpl: 'A', eyebrow: 'ent',
    muted: "No one taught you",
    punch: "how to budget\n{income like yours.}" },

  { id: 'B10', slug: 'villain-assume-paycheck', cat: 'Villain', theme: 'white', tpl: 'A', eyebrow: 'ent',
    muted: "Most budgeting apps",
    punch: "assume a\n{steady paycheck.}" },

  { id: 'B11', slug: 'villain-feels-impossible', cat: 'Villain', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent',
    muted: "Inconsistent income",
    punch: "makes budgeting\n{feel impossible.}" },

  { id: 'B12', slug: 'villain-never-taught', cat: 'Villain', theme: 'black', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "You were never taught\nhow to budget a paycheck",
    punch: "that {doesn't follow}\na schedule." },

  // ── Real fear (insight) ──
  { id: 'B13', slug: 'fear-not-knowing', cat: 'Real fear', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "Entrepreneurs don't fail to\npay down debt because\nthey don't want to.",
    punch: "They fail because they're\n{afraid of not knowing}\nwhen the next check\nis coming in." },

  // ── Paralysis ──
  { id: 'B14', slug: 'paralysis-you-freeze', cat: 'Paralysis', theme: 'black', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "{You freeze.}" },

  { id: 'B15', slug: 'paralysis-money-leaks', cat: 'Paralysis', theme: 'white', tpl: 'A', eyebrow: 'ent',
    muted: "Money that sits,",
    punch: "{leaks.}" },

  { id: 'B16', slug: 'paralysis-doesnt-stay', cat: 'Paralysis', theme: 'page', tpl: 'B', eyebrow: 'ent',
    punch: "Money that sits\n{doesn't stay put.}" },

  { id: 'B17', slug: 'paralysis-dont-move-it', cat: 'Paralysis', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "You don't move the money",
    punch: "because you don't know\n{when the next check}\nis coming." },

  { id: 'B18', slug: 'paralysis-nothing-decision', cat: 'Paralysis', theme: 'page', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "A little here.\nA little there.",
    punch: "{Nothing} feels\nlike a decision." },

  { id: 'B19', slug: 'paralysis-400-gone', cat: 'Paralysis', theme: 'black', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "By the end of the month,\n{$400 is gone.}",
    punch: "Nothing paid down.\nNothing saved.\nNothing to show for it." },

  { id: 'B20', slug: 'paralysis-check-to-check', cat: 'Paralysis', theme: 'glass-dark', tpl: 'B', eyebrow: 'ent',
    punch: "Living unpredictable\ncheck to {unpredictable\ncheck.}" },

  // ── Permission ──
  { id: 'B21', slug: 'permission-not-discipline', cat: 'Permission', theme: 'green', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "You don't need\nmore discipline.",
    punch: "You need a plan built\nfor {income like yours.}" },

  // ── Solution / mechanic ──
  { id: 'B22', slug: 'solution-every-dollar-job', cat: 'Solution', theme: 'green', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "Able gives every dollar",
    punch: "a job the moment\n{it arrives.}" },

  { id: 'B23', slug: 'solution-without-paycheck', cat: 'Solution', theme: 'page', tpl: 'B', eyebrow: 'ent',
    punch: "A budget that works\nwithout a {predictable\npaycheck.}" },

  { id: 'B24', slug: 'solution-lumpy-on-purpose', cat: 'Solution', theme: 'glass', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "Traditional apps assume\na steady paycheck.",
    punch: "{Able assumes} your income\nis lumpy, unpredictable,\nand rarely on schedule." },

  // ── Outcomes ──
  { id: 'B25', slug: 'outcome-pay-down-debt', cat: 'Outcomes', theme: 'green', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "Finally {pay down}\nyour debt." },

  { id: 'B26', slug: 'outcome-build-savings', cat: 'Outcomes', theme: 'green', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "Actually {build}\nyour savings." },

  { id: 'B27', slug: 'outcome-stop-check-to-check', cat: 'Outcomes', theme: 'green', tpl: 'A', eyebrow: 'ent',
    muted: "Stop living",
    punch: "{unpredictable check}\nto unpredictable check." },

  // ── Transformation ──
  { id: 'B28', slug: 'transform-i-am-able', cat: 'Transformation', theme: 'page', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "{I am able.}" },

  { id: 'B29', slug: 'transform-i-am-capable', cat: 'Transformation', theme: 'white', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "{I am capable.}" },

  { id: 'B30', slug: 'transform-it-is-predictable', cat: 'Transformation', theme: 'green', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "{It is predictable.}" },

  { id: 'B31', slug: 'transform-i-know-whats-coming', cat: 'Transformation', theme: 'glass', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "{I know}\nwhat's coming." },

  { id: 'B32', slug: 'transform-money-with-intention', cat: 'Transformation', theme: 'page', tpl: 'A', eyebrow: 'ent',
    muted: "My money moves",
    punch: "with {intention.}" },

  // ── New identity ──
  { id: 'B33', slug: 'identity-pay-down-slow-months', cat: 'New identity', theme: 'green', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "I am able to pay down debt,",
    punch: "even on {slow months.}" },

  { id: 'B34', slug: 'identity-save-no-second-guess', cat: 'New identity', theme: 'page', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "I am able to save",
    punch: "without {second-guessing.}" },

  { id: 'B35', slug: 'identity-predict-whats-coming', cat: 'New identity', theme: 'white', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "I am able to predict",
    punch: "{what is coming.}" },

  { id: 'B36', slug: 'identity-budget-inconsistent', cat: 'New identity', theme: 'green', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "I am able to budget",
    punch: "{inconsistent income.}" },

  // ── Transformation (added 2026-04-25) ──
  { id: 'B37', slug: 'transform-breathe-again', cat: 'Transformation', theme: 'glass-dark', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "From holding your breath\nwith bills →",
    punch: "Finally able to\n{breathe.}" },

  { id: 'B38', slug: 'identity-become-able', cat: 'New identity', theme: 'green', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "Able to pay down debt, even on slow months.\nAble to save without second-guessing.\nAble to predict what is coming.\nAble to budget inconsistent income.",
    punch: "{Become able.}" },

  { id: 'B39', slug: 'outcome-just-confidence', cat: 'Outcomes', theme: 'green', tpl: 'A', eyebrow: 'ent', size: 'sm',
    muted: "No more paralysis.\nNo more holding your breath.",
    punch: "{Just confidence.}\nEvery day." },

  { id: 'B40', slug: 'outcome-cost-of-waiting', cat: 'Outcomes', theme: 'black', tpl: 'B', eyebrow: 'ent',
    punch: "Every month you wait\nis another\n{$500–$1,000 gone.}" },

  { id: 'B41', slug: 'transform-unable-to-able', cat: 'Transformation', theme: 'green', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "From Unable\n→ {Able.}" },

  // ── Solution (added 2026-04-26 — value prop tagline) ──
  { id: 'B42', slug: 'solution-help-manage', cat: 'Solution', theme: 'green', tpl: 'B', eyebrow: 'ent', center: true,
    punch: "Able helps you manage\n{inconsistent income.}" },

];
